sonar.organization=ralixt
sonar.projectKey=ralixt_lpmde
sonar.projectName=La Petite Maison de l'Épouvante
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=var/log/cobertura.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**,var/**,public/**,migrations/**
