sonar.projectKey=ralixt_lpmde
sonar.organization=ralixt

sonar.projectName=La Petite Maison de l Épouvante
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.language=php
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit-unit.xml

sonar.exclusions=vendor/**,node_modules/**,public/build/**,var/**,migrations/**
sonar.coverage.exclusions=src/Kernel.php,src/Entity/**,migrations/**
