apiVersion: v1
kind: Secret
metadata:
  name: lpmde-sandbox-secrets
  namespace: lpmde-sandbox
type: Opaque
stringData:
  postgres-db: keycloak
  postgres-user: keycloak
  postgres-password: change-me-postgres

  keycloak-db-name: keycloak
  keycloak-db-user: keycloak
  keycloak-db-password: change-me-postgres
  keycloak-admin-user: admin
  keycloak-admin-password: admin

  rabbitmq-user: guest
  rabbitmq-password: guest
